name: Count Lines of Code
on:
  push:
    branches:
      - main
jobs:
  cloc:
    name: Count Lines of Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count Lines of Code
        uses: djdefi/cloc-action@main
      - run: 'echo ${{ github.event.inputs.message }} > todo.txt'
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: todo.txt
          channel: todo
