name: Count Lines of Code
on:
  push:
    branches:
      - main
jobs:
  cloc:
    name: CLOC
    runs-on: ubuntu-latest
    steps:
      - name: Count Lines of Code
        uses: djdefi/cloc-action@4
