name: Count Lines of Code
on:
  push:
    branches:
      - main
jobs:
  cloc:
    name: Count Lines of Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count Lines of Code
        uses: djdefi/cloc-action@main
      - name: Upload cloc output as a build artifact
        uses: actions/upload-artifact@v2
        with:
          name: cloc
          path: cloc.txt
